kind: pipeline
type: docker
name: default

steps:
- name: ibm
  image: node
  environment:
    IBM_CLOUD_API_KEY:
      from_secret: IBM_CLOUD_API_KEY
    IBM_CLOUD_REGION:
      from_secret: IBM_CLOUD_REGION
    IBM_CLOUD_ORG:
      from_secret: IBM_CLOUD_ORG
    IBM_CLOUD_SPACE:
      from_secret: IBM_CLOUD_SPACE
  commands:
  - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
  - ibmcloud plugin install cloud-functions
  - ibmcloud plugin list
  - ibmcloud login --apikey $IBM_CLOUD_API_KEY -r $IBM_CLOUD_REGION
  - ibmcloud target -o $IBM_CLOUD_ORG -s $IBM_CLOUD_SPACE
  - ibmcloud fn deploy --manifest manifest.yml
  - ibmcloud fn list
  
# pipeline:
#   build:
#     image: node
#     commands:
#       - npm install
#       - npm test
#   publish:
#     image: plugins/docker
#     repo: sakthik26/node-demo
#     secrets: [ docker_username, docker_password ]