---
language: python
install:
    - pip install requests flake8
script:
    - flake8 --ignore=E501
before_deploy:
    - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
deploy:
    provider: script
    script: bash deploy.sh